-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Convolution2D is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    kernel_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    kernel_ce0 : OUT STD_LOGIC;
    kernel_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of Convolution2D is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Convolution2D,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.232000,HLS_SYN_LAT=1132,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=14,HLS_SYN_FF=1135,HLS_SYN_LUT=2056,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_cast_fu_148_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_cast_reg_330 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_1_fu_158_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_1_reg_338 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_180_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_7_reg_343 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond3_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_cast_fu_186_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_cast_reg_348 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal j_1_fu_196_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal j_1_reg_356 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_1_fu_212_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_1_reg_364 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_4_fu_234_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_reg_369 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond1_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_261_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_reg_374 : STD_LOGIC_VECTOR (5 downto 0);
    signal n_1_fu_291_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal n_1_reg_382 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal exitcond_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal kernel_load_reg_397 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal input_load_reg_402 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_144_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_reg_407 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_139_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal i_reg_69 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond2_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_reg_80 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_reg_92 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_reg_105 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_1_reg_116 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_reg_128 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_cast_fu_276_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_15_cast_fu_306_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_16_cast_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_3_fu_168_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_cast_fu_176_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_164_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_222_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl2_cast_fu_230_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_cast_fu_218_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal m_cast_fu_202_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_240_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_249_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_6_cast_fu_245_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl1_cast_fu_257_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_cast_fu_267_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_271_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_cast_fu_297_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_10_fu_301_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal n_cast_fu_281_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_311_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_cast_11_fu_316_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_11_fu_320_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);

    component Convolution2D_dadbkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component Convolution2D_dmucud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    Convolution2D_dadbkb_U1 : component Convolution2D_dadbkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum_1_reg_116,
        din1 => tmp_1_reg_407,
        ce => ap_const_logic_1,
        dout => grp_fu_139_p2);

    Convolution2D_dmucud_U2 : component Convolution2D_dmucud
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => kernel_load_reg_397,
        din1 => input_load_reg_402,
        ce => ap_const_logic_1,
        dout => grp_fu_144_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_reg_69_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond2_fu_190_p2 = ap_const_lv1_1))) then 
                i_reg_69 <= i_1_reg_338;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_69 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    j_reg_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond3_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_80 <= ap_const_lv2_0;
            elsif (((exitcond1_fu_206_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_reg_80 <= j_1_reg_356;
            end if; 
        end if;
    end process;

    m_reg_105_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_190_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                m_reg_105 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (exitcond_fu_285_p2 = ap_const_lv1_1))) then 
                m_reg_105 <= m_1_reg_364;
            end if; 
        end if;
    end process;

    n_reg_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_206_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                n_reg_128 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                n_reg_128 <= n_1_reg_382;
            end if; 
        end if;
    end process;

    sum_1_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_206_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                sum_1_reg_116 <= sum_reg_92;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                sum_1_reg_116 <= grp_fu_139_p2;
            end if; 
        end if;
    end process;

    sum_reg_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_190_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                sum_reg_92 <= ap_const_lv64_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (exitcond_fu_285_p2 = ap_const_lv1_1))) then 
                sum_reg_92 <= sum_1_reg_116;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_1_reg_338 <= i_1_fu_158_p2;
                    i_cast_reg_330(1 downto 0) <= i_cast_fu_148_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                input_load_reg_402 <= input_r_q0;
                kernel_load_reg_397 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                j_1_reg_356 <= j_1_fu_196_p2;
                    j_cast_reg_348(1 downto 0) <= j_cast_fu_186_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                m_1_reg_364 <= m_1_fu_212_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                n_1_reg_382 <= n_1_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                tmp_1_reg_407 <= grp_fu_144_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_206_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                tmp_4_reg_369 <= tmp_4_fu_234_p2;
                tmp_8_reg_374 <= tmp_8_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond3_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_7_reg_343 <= tmp_7_fu_180_p2;
            end if;
        end if;
    end process;
    i_cast_reg_330(2) <= '0';
    j_cast_reg_348(2) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond3_fu_152_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, exitcond1_fu_206_p2, ap_CS_fsm_state5, exitcond_fu_285_p2, exitcond2_fu_190_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond3_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond2_fu_190_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((exitcond1_fu_206_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (exitcond_fu_285_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_done_assign_proc : process(ap_CS_fsm_state2, exitcond3_fu_152_p2)
    begin
        if (((exitcond3_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond3_fu_152_p2)
    begin
        if (((exitcond3_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_fu_206_p2 <= "1" when (m_reg_105 = ap_const_lv2_3) else "0";
    exitcond2_fu_190_p2 <= "1" when (j_reg_80 = ap_const_lv2_3) else "0";
    exitcond3_fu_152_p2 <= "1" when (i_reg_69 = ap_const_lv2_3) else "0";
    exitcond_fu_285_p2 <= "1" when (n_reg_128 = ap_const_lv2_3) else "0";
    i_1_fu_158_p2 <= std_logic_vector(unsigned(i_reg_69) + unsigned(ap_const_lv2_1));
    i_cast_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_69),3));
    input_r_address0 <= tmp_16_cast_fu_325_p1(5 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_196_p2 <= std_logic_vector(unsigned(j_reg_80) + unsigned(ap_const_lv2_1));
    j_cast_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_80),3));
    kernel_address0 <= tmp_15_cast_fu_306_p1(4 - 1 downto 0);

    kernel_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            kernel_ce0 <= ap_const_logic_1;
        else 
            kernel_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m_1_fu_212_p2 <= std_logic_vector(unsigned(m_reg_105) + unsigned(ap_const_lv2_1));
    m_cast_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_reg_105),3));
    n_1_fu_291_p2 <= std_logic_vector(unsigned(n_reg_128) + unsigned(ap_const_lv2_1));
    n_cast_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_reg_128),3));
    output_r_address0 <= tmp_10_cast_fu_276_p1(4 - 1 downto 0);

    output_r_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= sum_reg_92;

    output_r_we0_assign_proc : process(ap_CS_fsm_state4, exitcond1_fu_206_p2)
    begin
        if (((exitcond1_fu_206_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_cast_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_249_p3),6));
    p_shl2_cast_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_222_p3),5));
    p_shl_cast_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_168_p3),5));
        tmp_10_cast_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_271_p2),64));

    tmp_10_fu_301_p2 <= std_logic_vector(unsigned(tmp_4_reg_369) + unsigned(tmp_8_cast_fu_297_p1));
    tmp_11_fu_320_p2 <= std_logic_vector(unsigned(tmp_8_reg_374) + unsigned(tmp_cast_11_fu_316_p1));
        tmp_15_cast_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_301_p2),64));

    tmp_16_cast_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_320_p2),64));
    tmp_2_cast_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_80),5));
    tmp_2_fu_222_p3 <= (m_reg_105 & ap_const_lv2_0);
    tmp_3_fu_168_p3 <= (i_reg_69 & ap_const_lv2_0);
    tmp_4_cast_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_reg_105),5));
    tmp_4_fu_234_p2 <= std_logic_vector(unsigned(p_shl2_cast_fu_230_p1) - unsigned(tmp_4_cast_fu_218_p1));
    tmp_5_fu_240_p2 <= std_logic_vector(unsigned(m_cast_fu_202_p1) + unsigned(i_cast_reg_330));
    tmp_6_cast_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_240_p2),6));
    tmp_6_fu_249_p3 <= (tmp_5_fu_240_p2 & ap_const_lv2_0);
    tmp_7_fu_180_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_176_p1) - unsigned(tmp_cast_fu_164_p1));
    tmp_8_cast_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_reg_128),5));
    tmp_8_fu_261_p2 <= std_logic_vector(unsigned(tmp_6_cast_fu_245_p1) + unsigned(p_shl1_cast_fu_257_p1));
    tmp_9_fu_311_p2 <= std_logic_vector(unsigned(n_cast_fu_281_p1) + unsigned(j_cast_reg_348));
    tmp_cast_11_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_311_p2),6));
    tmp_cast_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_69),5));
    tmp_s_fu_271_p2 <= std_logic_vector(unsigned(tmp_7_reg_343) + unsigned(tmp_2_cast_fu_267_p1));
end behav;
