// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Convolution2D_HH_
#define _Convolution2D_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Convolution2D_dadbkb.h"
#include "Convolution2D_dmucud.h"

namespace ap_rtl {

struct Convolution2D : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<5> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_in< sc_lv<64> > input_r_q0;
    sc_out< sc_lv<4> > kernel_address0;
    sc_out< sc_logic > kernel_ce0;
    sc_in< sc_lv<64> > kernel_q0;
    sc_out< sc_lv<4> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<64> > output_r_d0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    Convolution2D(sc_module_name name);
    SC_HAS_PROCESS(Convolution2D);

    ~Convolution2D();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Convolution2D_dadbkb<1,5,64,64,64>* Convolution2D_dadbkb_U1;
    Convolution2D_dmucud<1,6,64,64,64>* Convolution2D_dmucud_U2;
    sc_signal< sc_lv<17> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > i_cast_fu_148_p1;
    sc_signal< sc_lv<3> > i_cast_reg_330;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > i_1_fu_158_p2;
    sc_signal< sc_lv<2> > i_1_reg_338;
    sc_signal< sc_lv<5> > tmp_7_fu_180_p2;
    sc_signal< sc_lv<5> > tmp_7_reg_343;
    sc_signal< sc_lv<1> > exitcond3_fu_152_p2;
    sc_signal< sc_lv<3> > j_cast_fu_186_p1;
    sc_signal< sc_lv<3> > j_cast_reg_348;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<2> > j_1_fu_196_p2;
    sc_signal< sc_lv<2> > j_1_reg_356;
    sc_signal< sc_lv<2> > m_1_fu_212_p2;
    sc_signal< sc_lv<2> > m_1_reg_364;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<5> > tmp_4_fu_234_p2;
    sc_signal< sc_lv<5> > tmp_4_reg_369;
    sc_signal< sc_lv<1> > exitcond1_fu_206_p2;
    sc_signal< sc_lv<6> > tmp_8_fu_261_p2;
    sc_signal< sc_lv<6> > tmp_8_reg_374;
    sc_signal< sc_lv<2> > n_1_fu_291_p2;
    sc_signal< sc_lv<2> > n_1_reg_382;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > exitcond_fu_285_p2;
    sc_signal< sc_lv<64> > kernel_load_reg_397;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > input_load_reg_402;
    sc_signal< sc_lv<64> > grp_fu_144_p2;
    sc_signal< sc_lv<64> > tmp_1_reg_407;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > grp_fu_139_p2;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<2> > i_reg_69;
    sc_signal< sc_lv<1> > exitcond2_fu_190_p2;
    sc_signal< sc_lv<2> > j_reg_80;
    sc_signal< sc_lv<64> > sum_reg_92;
    sc_signal< sc_lv<2> > m_reg_105;
    sc_signal< sc_lv<64> > sum_1_reg_116;
    sc_signal< sc_lv<2> > n_reg_128;
    sc_signal< sc_lv<64> > tmp_10_cast_fu_276_p1;
    sc_signal< sc_lv<64> > tmp_15_cast_fu_306_p1;
    sc_signal< sc_lv<64> > tmp_16_cast_fu_325_p1;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<4> > tmp_3_fu_168_p3;
    sc_signal< sc_lv<5> > p_shl_cast_fu_176_p1;
    sc_signal< sc_lv<5> > tmp_cast_fu_164_p1;
    sc_signal< sc_lv<4> > tmp_2_fu_222_p3;
    sc_signal< sc_lv<5> > p_shl2_cast_fu_230_p1;
    sc_signal< sc_lv<5> > tmp_4_cast_fu_218_p1;
    sc_signal< sc_lv<3> > m_cast_fu_202_p1;
    sc_signal< sc_lv<3> > tmp_5_fu_240_p2;
    sc_signal< sc_lv<5> > tmp_6_fu_249_p3;
    sc_signal< sc_lv<6> > tmp_6_cast_fu_245_p1;
    sc_signal< sc_lv<6> > p_shl1_cast_fu_257_p1;
    sc_signal< sc_lv<5> > tmp_2_cast_fu_267_p1;
    sc_signal< sc_lv<5> > tmp_s_fu_271_p2;
    sc_signal< sc_lv<5> > tmp_8_cast_fu_297_p1;
    sc_signal< sc_lv<5> > tmp_10_fu_301_p2;
    sc_signal< sc_lv<3> > n_cast_fu_281_p1;
    sc_signal< sc_lv<3> > tmp_9_fu_311_p2;
    sc_signal< sc_lv<6> > tmp_cast_11_fu_316_p1;
    sc_signal< sc_lv<6> > tmp_11_fu_320_p2;
    sc_signal< sc_lv<17> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<17> ap_ST_fsm_state1;
    static const sc_lv<17> ap_ST_fsm_state2;
    static const sc_lv<17> ap_ST_fsm_state3;
    static const sc_lv<17> ap_ST_fsm_state4;
    static const sc_lv<17> ap_ST_fsm_state5;
    static const sc_lv<17> ap_ST_fsm_state6;
    static const sc_lv<17> ap_ST_fsm_state7;
    static const sc_lv<17> ap_ST_fsm_state8;
    static const sc_lv<17> ap_ST_fsm_state9;
    static const sc_lv<17> ap_ST_fsm_state10;
    static const sc_lv<17> ap_ST_fsm_state11;
    static const sc_lv<17> ap_ST_fsm_state12;
    static const sc_lv<17> ap_ST_fsm_state13;
    static const sc_lv<17> ap_ST_fsm_state14;
    static const sc_lv<17> ap_ST_fsm_state15;
    static const sc_lv<17> ap_ST_fsm_state16;
    static const sc_lv<17> ap_ST_fsm_state17;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond1_fu_206_p2();
    void thread_exitcond2_fu_190_p2();
    void thread_exitcond3_fu_152_p2();
    void thread_exitcond_fu_285_p2();
    void thread_i_1_fu_158_p2();
    void thread_i_cast_fu_148_p1();
    void thread_input_r_address0();
    void thread_input_r_ce0();
    void thread_j_1_fu_196_p2();
    void thread_j_cast_fu_186_p1();
    void thread_kernel_address0();
    void thread_kernel_ce0();
    void thread_m_1_fu_212_p2();
    void thread_m_cast_fu_202_p1();
    void thread_n_1_fu_291_p2();
    void thread_n_cast_fu_281_p1();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_p_shl1_cast_fu_257_p1();
    void thread_p_shl2_cast_fu_230_p1();
    void thread_p_shl_cast_fu_176_p1();
    void thread_tmp_10_cast_fu_276_p1();
    void thread_tmp_10_fu_301_p2();
    void thread_tmp_11_fu_320_p2();
    void thread_tmp_15_cast_fu_306_p1();
    void thread_tmp_16_cast_fu_325_p1();
    void thread_tmp_2_cast_fu_267_p1();
    void thread_tmp_2_fu_222_p3();
    void thread_tmp_3_fu_168_p3();
    void thread_tmp_4_cast_fu_218_p1();
    void thread_tmp_4_fu_234_p2();
    void thread_tmp_5_fu_240_p2();
    void thread_tmp_6_cast_fu_245_p1();
    void thread_tmp_6_fu_249_p3();
    void thread_tmp_7_fu_180_p2();
    void thread_tmp_8_cast_fu_297_p1();
    void thread_tmp_8_fu_261_p2();
    void thread_tmp_9_fu_311_p2();
    void thread_tmp_cast_11_fu_316_p1();
    void thread_tmp_cast_fu_164_p1();
    void thread_tmp_s_fu_271_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
