// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Convolution2D.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Convolution2D::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Convolution2D::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<17> Convolution2D::ap_ST_fsm_state1 = "1";
const sc_lv<17> Convolution2D::ap_ST_fsm_state2 = "10";
const sc_lv<17> Convolution2D::ap_ST_fsm_state3 = "100";
const sc_lv<17> Convolution2D::ap_ST_fsm_state4 = "1000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state5 = "10000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state6 = "100000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state7 = "1000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state8 = "10000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state9 = "100000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state10 = "1000000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state11 = "10000000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state12 = "100000000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<17> Convolution2D::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<32> Convolution2D::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Convolution2D::ap_const_lv32_1 = "1";
const sc_lv<1> Convolution2D::ap_const_lv1_0 = "0";
const sc_lv<32> Convolution2D::ap_const_lv32_2 = "10";
const sc_lv<32> Convolution2D::ap_const_lv32_3 = "11";
const sc_lv<32> Convolution2D::ap_const_lv32_4 = "100";
const sc_lv<32> Convolution2D::ap_const_lv32_5 = "101";
const sc_lv<32> Convolution2D::ap_const_lv32_B = "1011";
const sc_lv<32> Convolution2D::ap_const_lv32_10 = "10000";
const sc_lv<2> Convolution2D::ap_const_lv2_0 = "00";
const sc_lv<1> Convolution2D::ap_const_lv1_1 = "1";
const sc_lv<64> Convolution2D::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> Convolution2D::ap_const_lv32_C = "1100";
const sc_lv<32> Convolution2D::ap_const_lv32_6 = "110";
const sc_lv<2> Convolution2D::ap_const_lv2_3 = "11";
const sc_lv<2> Convolution2D::ap_const_lv2_1 = "1";
const bool Convolution2D::ap_const_boolean_1 = true;

Convolution2D::Convolution2D(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Convolution2D_dadbkb_U1 = new Convolution2D_dadbkb<1,5,64,64,64>("Convolution2D_dadbkb_U1");
    Convolution2D_dadbkb_U1->clk(ap_clk);
    Convolution2D_dadbkb_U1->reset(ap_rst);
    Convolution2D_dadbkb_U1->din0(sum_1_reg_116);
    Convolution2D_dadbkb_U1->din1(tmp_1_reg_407);
    Convolution2D_dadbkb_U1->ce(ap_var_for_const0);
    Convolution2D_dadbkb_U1->dout(grp_fu_139_p2);
    Convolution2D_dmucud_U2 = new Convolution2D_dmucud<1,6,64,64,64>("Convolution2D_dmucud_U2");
    Convolution2D_dmucud_U2->clk(ap_clk);
    Convolution2D_dmucud_U2->reset(ap_rst);
    Convolution2D_dmucud_U2->din0(kernel_load_reg_397);
    Convolution2D_dmucud_U2->din1(input_load_reg_402);
    Convolution2D_dmucud_U2->ce(ap_var_for_const0);
    Convolution2D_dmucud_U2->dout(grp_fu_144_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_152_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_152_p2 );

    SC_METHOD(thread_exitcond1_fu_206_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( m_reg_105 );

    SC_METHOD(thread_exitcond2_fu_190_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_reg_80 );

    SC_METHOD(thread_exitcond3_fu_152_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_69 );

    SC_METHOD(thread_exitcond_fu_285_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( n_reg_128 );

    SC_METHOD(thread_i_1_fu_158_p2);
    sensitive << ( i_reg_69 );

    SC_METHOD(thread_i_cast_fu_148_p1);
    sensitive << ( i_reg_69 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_16_cast_fu_325_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_j_1_fu_196_p2);
    sensitive << ( j_reg_80 );

    SC_METHOD(thread_j_cast_fu_186_p1);
    sensitive << ( j_reg_80 );

    SC_METHOD(thread_kernel_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_15_cast_fu_306_p1 );

    SC_METHOD(thread_kernel_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_m_1_fu_212_p2);
    sensitive << ( m_reg_105 );

    SC_METHOD(thread_m_cast_fu_202_p1);
    sensitive << ( m_reg_105 );

    SC_METHOD(thread_n_1_fu_291_p2);
    sensitive << ( n_reg_128 );

    SC_METHOD(thread_n_cast_fu_281_p1);
    sensitive << ( n_reg_128 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_10_cast_fu_276_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_reg_92 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_206_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_257_p1);
    sensitive << ( tmp_6_fu_249_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_230_p1);
    sensitive << ( tmp_2_fu_222_p3 );

    SC_METHOD(thread_p_shl_cast_fu_176_p1);
    sensitive << ( tmp_3_fu_168_p3 );

    SC_METHOD(thread_tmp_10_cast_fu_276_p1);
    sensitive << ( tmp_s_fu_271_p2 );

    SC_METHOD(thread_tmp_10_fu_301_p2);
    sensitive << ( tmp_4_reg_369 );
    sensitive << ( tmp_8_cast_fu_297_p1 );

    SC_METHOD(thread_tmp_11_fu_320_p2);
    sensitive << ( tmp_8_reg_374 );
    sensitive << ( tmp_cast_11_fu_316_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_306_p1);
    sensitive << ( tmp_10_fu_301_p2 );

    SC_METHOD(thread_tmp_16_cast_fu_325_p1);
    sensitive << ( tmp_11_fu_320_p2 );

    SC_METHOD(thread_tmp_2_cast_fu_267_p1);
    sensitive << ( j_reg_80 );

    SC_METHOD(thread_tmp_2_fu_222_p3);
    sensitive << ( m_reg_105 );

    SC_METHOD(thread_tmp_3_fu_168_p3);
    sensitive << ( i_reg_69 );

    SC_METHOD(thread_tmp_4_cast_fu_218_p1);
    sensitive << ( m_reg_105 );

    SC_METHOD(thread_tmp_4_fu_234_p2);
    sensitive << ( p_shl2_cast_fu_230_p1 );
    sensitive << ( tmp_4_cast_fu_218_p1 );

    SC_METHOD(thread_tmp_5_fu_240_p2);
    sensitive << ( i_cast_reg_330 );
    sensitive << ( m_cast_fu_202_p1 );

    SC_METHOD(thread_tmp_6_cast_fu_245_p1);
    sensitive << ( tmp_5_fu_240_p2 );

    SC_METHOD(thread_tmp_6_fu_249_p3);
    sensitive << ( tmp_5_fu_240_p2 );

    SC_METHOD(thread_tmp_7_fu_180_p2);
    sensitive << ( p_shl_cast_fu_176_p1 );
    sensitive << ( tmp_cast_fu_164_p1 );

    SC_METHOD(thread_tmp_8_cast_fu_297_p1);
    sensitive << ( n_reg_128 );

    SC_METHOD(thread_tmp_8_fu_261_p2);
    sensitive << ( tmp_6_cast_fu_245_p1 );
    sensitive << ( p_shl1_cast_fu_257_p1 );

    SC_METHOD(thread_tmp_9_fu_311_p2);
    sensitive << ( j_cast_reg_348 );
    sensitive << ( n_cast_fu_281_p1 );

    SC_METHOD(thread_tmp_cast_11_fu_316_p1);
    sensitive << ( tmp_9_fu_311_p2 );

    SC_METHOD(thread_tmp_cast_fu_164_p1);
    sensitive << ( i_reg_69 );

    SC_METHOD(thread_tmp_s_fu_271_p2);
    sensitive << ( tmp_7_reg_343 );
    sensitive << ( tmp_2_cast_fu_267_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_152_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_206_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond_fu_285_p2 );
    sensitive << ( exitcond2_fu_190_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Convolution2D_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, kernel_address0, "(port)kernel_address0");
    sc_trace(mVcdFile, kernel_ce0, "(port)kernel_ce0");
    sc_trace(mVcdFile, kernel_q0, "(port)kernel_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_cast_fu_148_p1, "i_cast_fu_148_p1");
    sc_trace(mVcdFile, i_cast_reg_330, "i_cast_reg_330");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_158_p2, "i_1_fu_158_p2");
    sc_trace(mVcdFile, i_1_reg_338, "i_1_reg_338");
    sc_trace(mVcdFile, tmp_7_fu_180_p2, "tmp_7_fu_180_p2");
    sc_trace(mVcdFile, tmp_7_reg_343, "tmp_7_reg_343");
    sc_trace(mVcdFile, exitcond3_fu_152_p2, "exitcond3_fu_152_p2");
    sc_trace(mVcdFile, j_cast_fu_186_p1, "j_cast_fu_186_p1");
    sc_trace(mVcdFile, j_cast_reg_348, "j_cast_reg_348");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_1_fu_196_p2, "j_1_fu_196_p2");
    sc_trace(mVcdFile, j_1_reg_356, "j_1_reg_356");
    sc_trace(mVcdFile, m_1_fu_212_p2, "m_1_fu_212_p2");
    sc_trace(mVcdFile, m_1_reg_364, "m_1_reg_364");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_4_fu_234_p2, "tmp_4_fu_234_p2");
    sc_trace(mVcdFile, tmp_4_reg_369, "tmp_4_reg_369");
    sc_trace(mVcdFile, exitcond1_fu_206_p2, "exitcond1_fu_206_p2");
    sc_trace(mVcdFile, tmp_8_fu_261_p2, "tmp_8_fu_261_p2");
    sc_trace(mVcdFile, tmp_8_reg_374, "tmp_8_reg_374");
    sc_trace(mVcdFile, n_1_fu_291_p2, "n_1_fu_291_p2");
    sc_trace(mVcdFile, n_1_reg_382, "n_1_reg_382");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, exitcond_fu_285_p2, "exitcond_fu_285_p2");
    sc_trace(mVcdFile, kernel_load_reg_397, "kernel_load_reg_397");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, input_load_reg_402, "input_load_reg_402");
    sc_trace(mVcdFile, grp_fu_144_p2, "grp_fu_144_p2");
    sc_trace(mVcdFile, tmp_1_reg_407, "tmp_1_reg_407");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_139_p2, "grp_fu_139_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, i_reg_69, "i_reg_69");
    sc_trace(mVcdFile, exitcond2_fu_190_p2, "exitcond2_fu_190_p2");
    sc_trace(mVcdFile, j_reg_80, "j_reg_80");
    sc_trace(mVcdFile, sum_reg_92, "sum_reg_92");
    sc_trace(mVcdFile, m_reg_105, "m_reg_105");
    sc_trace(mVcdFile, sum_1_reg_116, "sum_1_reg_116");
    sc_trace(mVcdFile, n_reg_128, "n_reg_128");
    sc_trace(mVcdFile, tmp_10_cast_fu_276_p1, "tmp_10_cast_fu_276_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_306_p1, "tmp_15_cast_fu_306_p1");
    sc_trace(mVcdFile, tmp_16_cast_fu_325_p1, "tmp_16_cast_fu_325_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_3_fu_168_p3, "tmp_3_fu_168_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_176_p1, "p_shl_cast_fu_176_p1");
    sc_trace(mVcdFile, tmp_cast_fu_164_p1, "tmp_cast_fu_164_p1");
    sc_trace(mVcdFile, tmp_2_fu_222_p3, "tmp_2_fu_222_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_230_p1, "p_shl2_cast_fu_230_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_218_p1, "tmp_4_cast_fu_218_p1");
    sc_trace(mVcdFile, m_cast_fu_202_p1, "m_cast_fu_202_p1");
    sc_trace(mVcdFile, tmp_5_fu_240_p2, "tmp_5_fu_240_p2");
    sc_trace(mVcdFile, tmp_6_fu_249_p3, "tmp_6_fu_249_p3");
    sc_trace(mVcdFile, tmp_6_cast_fu_245_p1, "tmp_6_cast_fu_245_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_257_p1, "p_shl1_cast_fu_257_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_267_p1, "tmp_2_cast_fu_267_p1");
    sc_trace(mVcdFile, tmp_s_fu_271_p2, "tmp_s_fu_271_p2");
    sc_trace(mVcdFile, tmp_8_cast_fu_297_p1, "tmp_8_cast_fu_297_p1");
    sc_trace(mVcdFile, tmp_10_fu_301_p2, "tmp_10_fu_301_p2");
    sc_trace(mVcdFile, n_cast_fu_281_p1, "n_cast_fu_281_p1");
    sc_trace(mVcdFile, tmp_9_fu_311_p2, "tmp_9_fu_311_p2");
    sc_trace(mVcdFile, tmp_cast_11_fu_316_p1, "tmp_cast_11_fu_316_p1");
    sc_trace(mVcdFile, tmp_11_fu_320_p2, "tmp_11_fu_320_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("Convolution2D.hdltvin.dat");
    mHdltvoutHandle.open("Convolution2D.hdltvout.dat");
}

Convolution2D::~Convolution2D() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Convolution2D_dadbkb_U1;
    delete Convolution2D_dmucud_U2;
}

void Convolution2D::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Convolution2D::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_190_p2.read(), ap_const_lv1_1))) {
        i_reg_69 = i_1_reg_338.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_69 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_0))) {
        j_reg_80 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_206_p2.read(), ap_const_lv1_1))) {
        j_reg_80 = j_1_reg_356.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_190_p2.read()))) {
        m_reg_105 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_285_p2.read(), ap_const_lv1_1))) {
        m_reg_105 = m_1_reg_364.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_206_p2.read()))) {
        n_reg_128 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        n_reg_128 = n_1_reg_382.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_206_p2.read()))) {
        sum_1_reg_116 = sum_reg_92.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        sum_1_reg_116 = grp_fu_139_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_190_p2.read()))) {
        sum_reg_92 = ap_const_lv64_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_285_p2.read(), ap_const_lv1_1))) {
        sum_reg_92 = sum_1_reg_116.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_338 = i_1_fu_158_p2.read();
        i_cast_reg_330 = i_cast_fu_148_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        input_load_reg_402 = input_r_q0.read();
        kernel_load_reg_397 = kernel_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_1_reg_356 = j_1_fu_196_p2.read();
        j_cast_reg_348 = j_cast_fu_186_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        m_1_reg_364 = m_1_fu_212_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        n_1_reg_382 = n_1_fu_291_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_1_reg_407 = grp_fu_144_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_206_p2.read()))) {
        tmp_4_reg_369 = tmp_4_fu_234_p2.read();
        tmp_8_reg_374 = tmp_8_fu_261_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_0))) {
        tmp_7_reg_343 = tmp_7_fu_180_p2.read();
    }
}

void Convolution2D::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Convolution2D::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void Convolution2D::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void Convolution2D::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void Convolution2D::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Convolution2D::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Convolution2D::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void Convolution2D::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void Convolution2D::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void Convolution2D::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void Convolution2D::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Convolution2D::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Convolution2D::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Convolution2D::thread_exitcond1_fu_206_p2() {
    exitcond1_fu_206_p2 = (!m_reg_105.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(m_reg_105.read() == ap_const_lv2_3);
}

void Convolution2D::thread_exitcond2_fu_190_p2() {
    exitcond2_fu_190_p2 = (!j_reg_80.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_80.read() == ap_const_lv2_3);
}

void Convolution2D::thread_exitcond3_fu_152_p2() {
    exitcond3_fu_152_p2 = (!i_reg_69.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_69.read() == ap_const_lv2_3);
}

void Convolution2D::thread_exitcond_fu_285_p2() {
    exitcond_fu_285_p2 = (!n_reg_128.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(n_reg_128.read() == ap_const_lv2_3);
}

void Convolution2D::thread_i_1_fu_158_p2() {
    i_1_fu_158_p2 = (!i_reg_69.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_reg_69.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Convolution2D::thread_i_cast_fu_148_p1() {
    i_cast_fu_148_p1 = esl_zext<3,2>(i_reg_69.read());
}

void Convolution2D::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<5>) (tmp_16_cast_fu_325_p1.read());
}

void Convolution2D::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void Convolution2D::thread_j_1_fu_196_p2() {
    j_1_fu_196_p2 = (!j_reg_80.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_reg_80.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Convolution2D::thread_j_cast_fu_186_p1() {
    j_cast_fu_186_p1 = esl_zext<3,2>(j_reg_80.read());
}

void Convolution2D::thread_kernel_address0() {
    kernel_address0 =  (sc_lv<4>) (tmp_15_cast_fu_306_p1.read());
}

void Convolution2D::thread_kernel_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        kernel_ce0 = ap_const_logic_1;
    } else {
        kernel_ce0 = ap_const_logic_0;
    }
}

void Convolution2D::thread_m_1_fu_212_p2() {
    m_1_fu_212_p2 = (!m_reg_105.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(m_reg_105.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Convolution2D::thread_m_cast_fu_202_p1() {
    m_cast_fu_202_p1 = esl_zext<3,2>(m_reg_105.read());
}

void Convolution2D::thread_n_1_fu_291_p2() {
    n_1_fu_291_p2 = (!n_reg_128.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(n_reg_128.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Convolution2D::thread_n_cast_fu_281_p1() {
    n_cast_fu_281_p1 = esl_zext<3,2>(n_reg_128.read());
}

void Convolution2D::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<4>) (tmp_10_cast_fu_276_p1.read());
}

void Convolution2D::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void Convolution2D::thread_output_r_d0() {
    output_r_d0 = sum_reg_92.read();
}

void Convolution2D::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_206_p2.read(), ap_const_lv1_1))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void Convolution2D::thread_p_shl1_cast_fu_257_p1() {
    p_shl1_cast_fu_257_p1 = esl_zext<6,5>(tmp_6_fu_249_p3.read());
}

void Convolution2D::thread_p_shl2_cast_fu_230_p1() {
    p_shl2_cast_fu_230_p1 = esl_zext<5,4>(tmp_2_fu_222_p3.read());
}

void Convolution2D::thread_p_shl_cast_fu_176_p1() {
    p_shl_cast_fu_176_p1 = esl_zext<5,4>(tmp_3_fu_168_p3.read());
}

void Convolution2D::thread_tmp_10_cast_fu_276_p1() {
    tmp_10_cast_fu_276_p1 = esl_sext<64,5>(tmp_s_fu_271_p2.read());
}

void Convolution2D::thread_tmp_10_fu_301_p2() {
    tmp_10_fu_301_p2 = (!tmp_4_reg_369.read().is_01() || !tmp_8_cast_fu_297_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_4_reg_369.read()) + sc_biguint<5>(tmp_8_cast_fu_297_p1.read()));
}

void Convolution2D::thread_tmp_11_fu_320_p2() {
    tmp_11_fu_320_p2 = (!tmp_8_reg_374.read().is_01() || !tmp_cast_11_fu_316_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_8_reg_374.read()) + sc_biguint<6>(tmp_cast_11_fu_316_p1.read()));
}

void Convolution2D::thread_tmp_15_cast_fu_306_p1() {
    tmp_15_cast_fu_306_p1 = esl_sext<64,5>(tmp_10_fu_301_p2.read());
}

void Convolution2D::thread_tmp_16_cast_fu_325_p1() {
    tmp_16_cast_fu_325_p1 = esl_zext<64,6>(tmp_11_fu_320_p2.read());
}

void Convolution2D::thread_tmp_2_cast_fu_267_p1() {
    tmp_2_cast_fu_267_p1 = esl_zext<5,2>(j_reg_80.read());
}

void Convolution2D::thread_tmp_2_fu_222_p3() {
    tmp_2_fu_222_p3 = esl_concat<2,2>(m_reg_105.read(), ap_const_lv2_0);
}

void Convolution2D::thread_tmp_3_fu_168_p3() {
    tmp_3_fu_168_p3 = esl_concat<2,2>(i_reg_69.read(), ap_const_lv2_0);
}

void Convolution2D::thread_tmp_4_cast_fu_218_p1() {
    tmp_4_cast_fu_218_p1 = esl_zext<5,2>(m_reg_105.read());
}

void Convolution2D::thread_tmp_4_fu_234_p2() {
    tmp_4_fu_234_p2 = (!p_shl2_cast_fu_230_p1.read().is_01() || !tmp_4_cast_fu_218_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl2_cast_fu_230_p1.read()) - sc_biguint<5>(tmp_4_cast_fu_218_p1.read()));
}

void Convolution2D::thread_tmp_5_fu_240_p2() {
    tmp_5_fu_240_p2 = (!m_cast_fu_202_p1.read().is_01() || !i_cast_reg_330.read().is_01())? sc_lv<3>(): (sc_biguint<3>(m_cast_fu_202_p1.read()) + sc_biguint<3>(i_cast_reg_330.read()));
}

void Convolution2D::thread_tmp_6_cast_fu_245_p1() {
    tmp_6_cast_fu_245_p1 = esl_zext<6,3>(tmp_5_fu_240_p2.read());
}

void Convolution2D::thread_tmp_6_fu_249_p3() {
    tmp_6_fu_249_p3 = esl_concat<3,2>(tmp_5_fu_240_p2.read(), ap_const_lv2_0);
}

void Convolution2D::thread_tmp_7_fu_180_p2() {
    tmp_7_fu_180_p2 = (!p_shl_cast_fu_176_p1.read().is_01() || !tmp_cast_fu_164_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl_cast_fu_176_p1.read()) - sc_biguint<5>(tmp_cast_fu_164_p1.read()));
}

void Convolution2D::thread_tmp_8_cast_fu_297_p1() {
    tmp_8_cast_fu_297_p1 = esl_zext<5,2>(n_reg_128.read());
}

void Convolution2D::thread_tmp_8_fu_261_p2() {
    tmp_8_fu_261_p2 = (!tmp_6_cast_fu_245_p1.read().is_01() || !p_shl1_cast_fu_257_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_6_cast_fu_245_p1.read()) + sc_biguint<6>(p_shl1_cast_fu_257_p1.read()));
}

void Convolution2D::thread_tmp_9_fu_311_p2() {
    tmp_9_fu_311_p2 = (!n_cast_fu_281_p1.read().is_01() || !j_cast_reg_348.read().is_01())? sc_lv<3>(): (sc_biguint<3>(n_cast_fu_281_p1.read()) + sc_biguint<3>(j_cast_reg_348.read()));
}

void Convolution2D::thread_tmp_cast_11_fu_316_p1() {
    tmp_cast_11_fu_316_p1 = esl_zext<6,3>(tmp_9_fu_311_p2.read());
}

void Convolution2D::thread_tmp_cast_fu_164_p1() {
    tmp_cast_fu_164_p1 = esl_zext<5,2>(i_reg_69.read());
}

void Convolution2D::thread_tmp_s_fu_271_p2() {
    tmp_s_fu_271_p2 = (!tmp_7_reg_343.read().is_01() || !tmp_2_cast_fu_267_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_7_reg_343.read()) + sc_biguint<5>(tmp_2_cast_fu_267_p1.read()));
}

void Convolution2D::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond2_fu_190_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond1_fu_206_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond_fu_285_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXX";
            break;
    }
}

void Convolution2D::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_address0\" :  \"" << input_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce0\" :  \"" << input_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q0\" :  \"" << input_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_address0\" :  \"" << kernel_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_ce0\" :  \"" << kernel_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_q0\" :  \"" << kernel_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_address0\" :  \"" << output_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_ce0\" :  \"" << output_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_we0\" :  \"" << output_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_d0\" :  \"" << output_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

