// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Convolution2D,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.232000,HLS_SYN_LAT=1132,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=14,HLS_SYN_FF=1135,HLS_SYN_LUT=2056,HLS_VERSION=2018_3}" *)

module Convolution2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        kernel_address0,
        kernel_ce0,
        kernel_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] input_r_address0;
output   input_r_ce0;
input  [63:0] input_r_q0;
output  [3:0] kernel_address0;
output   kernel_ce0;
input  [63:0] kernel_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [63:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg kernel_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] i_cast_fu_148_p1;
reg   [2:0] i_cast_reg_330;
wire    ap_CS_fsm_state2;
wire   [1:0] i_1_fu_158_p2;
reg   [1:0] i_1_reg_338;
wire   [4:0] tmp_7_fu_180_p2;
reg   [4:0] tmp_7_reg_343;
wire   [0:0] exitcond3_fu_152_p2;
wire   [2:0] j_cast_fu_186_p1;
reg   [2:0] j_cast_reg_348;
wire    ap_CS_fsm_state3;
wire   [1:0] j_1_fu_196_p2;
reg   [1:0] j_1_reg_356;
wire   [1:0] m_1_fu_212_p2;
reg   [1:0] m_1_reg_364;
wire    ap_CS_fsm_state4;
wire   [4:0] tmp_4_fu_234_p2;
reg   [4:0] tmp_4_reg_369;
wire   [0:0] exitcond1_fu_206_p2;
wire   [5:0] tmp_8_fu_261_p2;
reg   [5:0] tmp_8_reg_374;
wire   [1:0] n_1_fu_291_p2;
reg   [1:0] n_1_reg_382;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_fu_285_p2;
reg   [63:0] kernel_load_reg_397;
wire    ap_CS_fsm_state6;
reg   [63:0] input_load_reg_402;
wire   [63:0] grp_fu_144_p2;
reg   [63:0] tmp_1_reg_407;
wire    ap_CS_fsm_state12;
wire   [63:0] grp_fu_139_p2;
wire    ap_CS_fsm_state17;
reg   [1:0] i_reg_69;
wire   [0:0] exitcond2_fu_190_p2;
reg   [1:0] j_reg_80;
reg   [63:0] sum_reg_92;
reg   [1:0] m_reg_105;
reg   [63:0] sum_1_reg_116;
reg   [1:0] n_reg_128;
wire  signed [63:0] tmp_10_cast_fu_276_p1;
wire  signed [63:0] tmp_15_cast_fu_306_p1;
wire   [63:0] tmp_16_cast_fu_325_p1;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state7;
wire   [3:0] tmp_3_fu_168_p3;
wire   [4:0] p_shl_cast_fu_176_p1;
wire   [4:0] tmp_cast_fu_164_p1;
wire   [3:0] tmp_2_fu_222_p3;
wire   [4:0] p_shl2_cast_fu_230_p1;
wire   [4:0] tmp_4_cast_fu_218_p1;
wire   [2:0] m_cast_fu_202_p1;
wire   [2:0] tmp_5_fu_240_p2;
wire   [4:0] tmp_6_fu_249_p3;
wire   [5:0] tmp_6_cast_fu_245_p1;
wire   [5:0] p_shl1_cast_fu_257_p1;
wire   [4:0] tmp_2_cast_fu_267_p1;
wire   [4:0] tmp_s_fu_271_p2;
wire   [4:0] tmp_8_cast_fu_297_p1;
wire   [4:0] tmp_10_fu_301_p2;
wire   [2:0] n_cast_fu_281_p1;
wire   [2:0] tmp_9_fu_311_p2;
wire   [5:0] tmp_cast_11_fu_316_p1;
wire   [5:0] tmp_11_fu_320_p2;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
end

Convolution2D_dadbkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
Convolution2D_dadbkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_reg_116),
    .din1(tmp_1_reg_407),
    .ce(1'b1),
    .dout(grp_fu_139_p2)
);

Convolution2D_dmucud #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
Convolution2D_dmucud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kernel_load_reg_397),
    .din1(input_load_reg_402),
    .ce(1'b1),
    .dout(grp_fu_144_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_190_p2 == 1'd1))) begin
        i_reg_69 <= i_1_reg_338;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_69 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_80 <= 2'd0;
    end else if (((exitcond1_fu_206_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        j_reg_80 <= j_1_reg_356;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        m_reg_105 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond_fu_285_p2 == 1'd1))) begin
        m_reg_105 <= m_1_reg_364;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_206_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        n_reg_128 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        n_reg_128 <= n_1_reg_382;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_206_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sum_1_reg_116 <= sum_reg_92;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        sum_1_reg_116 <= grp_fu_139_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        sum_reg_92 <= 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond_fu_285_p2 == 1'd1))) begin
        sum_reg_92 <= sum_1_reg_116;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_338 <= i_1_fu_158_p2;
        i_cast_reg_330[1 : 0] <= i_cast_fu_148_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_load_reg_402 <= input_r_q0;
        kernel_load_reg_397 <= kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_1_reg_356 <= j_1_fu_196_p2;
        j_cast_reg_348[1 : 0] <= j_cast_fu_186_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        m_1_reg_364 <= m_1_fu_212_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        n_1_reg_382 <= n_1_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_1_reg_407 <= grp_fu_144_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_206_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_4_reg_369 <= tmp_4_fu_234_p2;
        tmp_8_reg_374 <= tmp_8_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_7_reg_343 <= tmp_7_fu_180_p2;
    end
end

always @ (*) begin
    if (((exitcond3_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond3_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kernel_ce0 = 1'b1;
    end else begin
        kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_206_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond3_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_190_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond1_fu_206_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (exitcond_fu_285_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign exitcond1_fu_206_p2 = ((m_reg_105 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond2_fu_190_p2 = ((j_reg_80 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond3_fu_152_p2 = ((i_reg_69 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond_fu_285_p2 = ((n_reg_128 == 2'd3) ? 1'b1 : 1'b0);

assign i_1_fu_158_p2 = (i_reg_69 + 2'd1);

assign i_cast_fu_148_p1 = i_reg_69;

assign input_r_address0 = tmp_16_cast_fu_325_p1;

assign j_1_fu_196_p2 = (j_reg_80 + 2'd1);

assign j_cast_fu_186_p1 = j_reg_80;

assign kernel_address0 = tmp_15_cast_fu_306_p1;

assign m_1_fu_212_p2 = (m_reg_105 + 2'd1);

assign m_cast_fu_202_p1 = m_reg_105;

assign n_1_fu_291_p2 = (n_reg_128 + 2'd1);

assign n_cast_fu_281_p1 = n_reg_128;

assign output_r_address0 = tmp_10_cast_fu_276_p1;

assign output_r_d0 = sum_reg_92;

assign p_shl1_cast_fu_257_p1 = tmp_6_fu_249_p3;

assign p_shl2_cast_fu_230_p1 = tmp_2_fu_222_p3;

assign p_shl_cast_fu_176_p1 = tmp_3_fu_168_p3;

assign tmp_10_cast_fu_276_p1 = $signed(tmp_s_fu_271_p2);

assign tmp_10_fu_301_p2 = (tmp_4_reg_369 + tmp_8_cast_fu_297_p1);

assign tmp_11_fu_320_p2 = (tmp_8_reg_374 + tmp_cast_11_fu_316_p1);

assign tmp_15_cast_fu_306_p1 = $signed(tmp_10_fu_301_p2);

assign tmp_16_cast_fu_325_p1 = tmp_11_fu_320_p2;

assign tmp_2_cast_fu_267_p1 = j_reg_80;

assign tmp_2_fu_222_p3 = {{m_reg_105}, {2'd0}};

assign tmp_3_fu_168_p3 = {{i_reg_69}, {2'd0}};

assign tmp_4_cast_fu_218_p1 = m_reg_105;

assign tmp_4_fu_234_p2 = (p_shl2_cast_fu_230_p1 - tmp_4_cast_fu_218_p1);

assign tmp_5_fu_240_p2 = (m_cast_fu_202_p1 + i_cast_reg_330);

assign tmp_6_cast_fu_245_p1 = tmp_5_fu_240_p2;

assign tmp_6_fu_249_p3 = {{tmp_5_fu_240_p2}, {2'd0}};

assign tmp_7_fu_180_p2 = (p_shl_cast_fu_176_p1 - tmp_cast_fu_164_p1);

assign tmp_8_cast_fu_297_p1 = n_reg_128;

assign tmp_8_fu_261_p2 = (tmp_6_cast_fu_245_p1 + p_shl1_cast_fu_257_p1);

assign tmp_9_fu_311_p2 = (n_cast_fu_281_p1 + j_cast_reg_348);

assign tmp_cast_11_fu_316_p1 = tmp_9_fu_311_p2;

assign tmp_cast_fu_164_p1 = i_reg_69;

assign tmp_s_fu_271_p2 = (tmp_7_reg_343 + tmp_2_cast_fu_267_p1);

always @ (posedge ap_clk) begin
    i_cast_reg_330[2] <= 1'b0;
    j_cast_reg_348[2] <= 1'b0;
end

endmodule //Convolution2D
